Section "InputClass"
  Identifier "Keyboard catchall"
  MatchIsKeyboard "on"
  Option "XkbModel" "pc104"
  Option "XkbLayout" "us,ara"
  Option "XkbOptions" "grp:win_space_toggle caps:swapescape keypad:pointerkeys"
  Option "XkbVariant" "dvorak-l,"
EndSection
