#!/bin/sh

#######################################################
# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
# By: Anas Elgarhy: @anas-elgarhy or @anaselgarhy
####################################################


# Terminal
export TERMINAL=kitty

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap -model pc101 -layout us,ar -variant ,, -option grp:win_space_toggle &
/bin/stickykeys &
nitrogen --restore &
nm-applet &
copyq &
polybar &

# eww -c $HOME/.config/eww/eww-bar --restart open bar &

bspc monitor -d www dev sys chat img vid mus vbox gfx \;

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52

bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle false

# Rules
bspc rule -a Gimp desktop='^9' state=floating follow=on
bspc rule -a firefoxdeveloperedition desktop='^1' state=tiling follow=on
bspc rule -a "Tor Browser" desktop='^10' state=tiling follow=off
bspc rule -a "keepassxc" desktop='^10' state=tiling follow=on
bspc rule -a "discord" desktop='^4' state=tiling follow=on
bspc rule -a "jetbrains-idea" desktop='^2' state=tiling follow=on
bspc rule -a "jetbrains-pycharm" desktop='^2' state=tiling follow=on
bspc rule -a "jetbrains-clion" desktop='^2' state=tiling follow=on
bspc rule -a "jetbrains-webstorm" desktop='^2' state=tiling follow=on
bspc rule -a "jetbrains-rubymine" desktop='^2' state=tiling follow=on
bspc rule -a "jetbrains-goland" desktop='^2' state=tiling follow=on
